name: Build & Deploy

on: [push]

permissions:
  id-token: read
  contents: read

jobs:
  build:
    name: Build and test code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: yarn install --immutable-cache
    - run: yarn verify
