name: Build & Deploy

on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
    - run: yarn install --immutable-cache
    - run: yarn verify
    - uses: actions/upload-artifact@v2
      with:
        name: ui
        path: ./ui/public
    - uses: actions/upload-artifact@v2
      with:
        name: service
        path: ./service/dist
  deploy:
    needs: build
    name: Deploy cloudformation stack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
    - run: yarn install --immutable-cache
    - uses: actions/download-artifact@v2
      with:
        name: ui
        path: ./ui/public
    - uses: actions/download-artifact@v2
      with:
        name: service
        path: ./service/dist
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - run: yarn deploy